language: generic

sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      env: CXX="g++-7" CC="gcc-7"
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-7
            - g++-7
            - cmake
            - cmake-data
            - binutils-dev
            - zlib1g-dev
            - libc6-dev
            - libboost-system-dev
            - libboost-program-options-dev
            - libboost-filesystem-dev
            - linux-libc-dev
          sources: &sources
            - ubuntu-toolchain-r-test
    - os: linux
      env: CXX="g++-6" CC="gcc-6"
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-6
            - g++-6
            - cmake
            - cmake-data
            - binutils-dev
            - zlib1g-dev
            - libc6-dev
            - libboost-system-dev
            - libboost-program-options-dev
            - libboost-filesystem-dev
            - linux-libc-dev
          sources: *sources
    - os: linux
      env: CXX="g++-8" CC="gcc-8"
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-8
            - g++-8
            - cmake
            - cmake-data
            - binutils-dev
            - zlib1g-dev
            - libc6-dev
            - libboost-system-dev
            - libboost-program-options-dev
            - libboost-filesystem-dev
            - linux-libc-dev
          sources: *sources
    - os: linux
      env: CXX="clang++-5.0" CC="clang-5.0"
      compiler: clang
      addons:
        apt:
          packages:
            - clang-5.0
            - g++-5
            - cmake
            - cmake-data
            - binutils-dev
            - zlib1g-dev
            - libc6-dev
            - libboost-system-dev
            - libboost-program-options-dev
            - libboost-filesystem-dev
            - linux-libc-dev
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
    - os: linux
      env: CXX="clang++-4.0" CC="clang-4.0"
      compiler: clang
      addons:
        apt:
          packages:
            - clang-4.0
            - g++-5
            - cmake
            - cmake-data
            - binutils-dev
            - zlib1g-dev
            - libc6-dev
            - libboost-system-dev
            - libboost-program-options-dev
            - libboost-filesystem-dev
            - linux-libc-dev
          sources:
            - llvm-toolchain-trusty-4.0
            - ubuntu-toolchain-r-test

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/otf2-2.1

install:
  - OTF2_VERSION=2.1 # Update cache too when changing this!
  - OTF2_DIR=${TRAVIS_BUILD_DIR}/deps/otf2-${OTF2_VERSION}
  - |
    if [ -z "$(ls -A ${OTF2_DIR})" ]; then
      wget http://www.vi-hps.org/upload/packages/otf2/otf2-${OTF2_VERSION}.tar.gz
      tar -xf otf2-${OTF2_VERSION}.tar.gz
      (cd otf2-${OTF2_VERSION} && ./configure --prefix=${OTF2_DIR} && make -j2 install)
    fi
  - export CMAKE_PREFIX_PATH=${OTF2_DIR}:${CMAKE_PREFIX_PATH}

before_script:
  - sudo apt-get --no-install-suggests --no-install-recommends --force-yes install libiberty-dev

script:
  - cmake --version
  - cmake . -DUSE_RADARE=OFF -DUSE_PERF_CLOCKID=OFF
  - make
  - ctest -V .

before_deploy:
  - sudo pip install git-archive-all
  - cmake .
  - make dist

deploy:
  provider: releases
  api_key:
    secure: gzyV3ulr2N8TrNZp7piO90BVjZi4JwGNOW9/sXOAXwmjvTdrc79AzVUcIwnT9jUyKRV1YvnvAGJ9wGZ3sx+r8wGBsqHTfGYmZX3hOJyczlh4KeQ+Bz2v4k6EaXSKMrAeMsZ6v4PHcwYL53KneMybOlm3Drd3J1D1I+skhXhuATrTXVinArwdZNuiL7B40a0WVIUhgUrxOlB89x2AQ6gNqjsnGyXZJukncEfSRAXoEs9UDABbAI7WftPJ+oEk+qyn8U9ApWuB3wdx9HidW9JDxIIB9OwVWYyCRerQXJVzrQzWRCiC5wJFzo13PSev33QaHoav7E0q0ngT7lfQtlypsN7/ZTAL4em5iBgE5xJUn87ceOL9rzg26ll3gl8Xw8Gawkbs04ev1npfjpYd/w3I1Qf18OATwDMXc5/E0nhDhi6mB14JunyTtGmv46raV42syqYf2qqY9IZwp+YVTbhWdnmNynG30SGcN1Tiix9Sv+wXe1un5Cb2wKbPgCx1gx/ipgdIG387nT2CsnLjkfMRWdUORHulm7fIWSJNzVkQSeXnq7pcoBs1A5J1BHcLVp/+44kJtcKELJza59uOTtotQZjitCFCZQiYYo5+d2KTV0n7MN22qkw1yFEVOzy9V4hg1q5DyS9CaEhNUShGQ6FvWh6UGdAZ/T8XtrXxOKdiYA8=
  file_glob: true
  file: ${HOME}/build/${TRAVIS_REPO_SLUG}/lo2s*.tar.bz2
  skip_cleanup: true
  on:
    repo: tud-zih-energy/lo2s
    tags: true
